### ISSUE TITLE
为什么 0.1 + 0.2 = 0.300000004 · Why's THE Design? · /whys-the-design-floating-point-arithmetic

### ISSUE THREAD

**Issue by draveness** [draveness/blog-comments#194]
https://draveness.me/whys-the-design-floating-point-arithmetic 

 面向信仰编程 - Draveness's Blog

**Comment by yuchanns** [comment]
哈哈，周六的时候刚和朋友吐槽js，`"10"+1`和`"10"-1`

**Comment by draveness** [comment]
> 哈哈，周六的时候刚和朋友吐槽js，`"10"+1`和`"10"-1`

你这挺晚的...

**Comment by liucy-eve** [comment]
深入浅出，好文

**Comment by Cherrison** [comment]
csapp 2.4节...以及配套实验 lab1

**Comment by f4nyc** [comment]
【使用二进制表达十进制的小数时，某些数字无法被有限位的二进制小数表示；】
来补充一下某些数字是哪些以及为什么：
根据定义，二进制有限位数小数可以写作<img src="https://render.githubusercontent.com/render/math?math=\frac{a}{2^b}">的形式,十进制有限位数小数可以写作<img src="https://render.githubusercontent.com/render/math?math=\frac{a}{10^b}">的形式
而<img src="https://render.githubusercontent.com/render/math?math=\frac{a}{2^b} =\frac{a*5^b}{10^b}">，很显然二进制的有限位数小数是十进制有限位数小数的子集。
甚至扩展一下：
在k进制下(k>1)，任何形如a/b，且b的质因子不是k质因子的子集的数均为无限循环小数。

**Comment by clanaid** [comment]
配图还有趣，请问是用什么软件绘制的？

**Comment by juliofeng** [comment]
牛通

**Comment by lsunky** [comment]
如果再配上定点数这个解决浮点数精度问题的解决方案就更好了。
