### ISSUE TITLE
Go 语言的代码生成机制 | Go 语言设计与实现 · /golang-code-gen

### ISSUE THREAD

**Issue by draveness** [draveness/blog-comments#199]
https://draveness.me/golang-code-gen

 Go 语言的代码生成机制

**Comment by catundercar** [comment]
大哥，有时间可以出一期pprof的教程嘛。。

**Comment by draveness** [comment]
> 大哥，有时间可以出一期pprof的教程嘛。。

这个题目不错，不过教程可能不会写，这里应该会看看它是怎么做 Profile 的

**Comment by catundercar** [comment]
期待，小弟主要是看不太懂图，然后那些指数代表什么意义，不知道怎么入手，害。

**Comment by ghost** [comment]
大哥是陕西人吗
