### ISSUE TITLE
Go 语言数据库的实现原理 | Go 语言设计与实现 · /golang-database-sql

### ISSUE THREAD

**Issue by draveness** [draveness/blog-comments#209]
https://draveness.me/golang/docs/part4-advanced/ch09-stdlib/golang-database-sql/

 Go 语言数据库的实现原理

**Comment by lixianyang** [comment]
通读了一遍，有个整体印象，后面每个部分再细刷一遍。感谢博主大大

**Comment by wujunze** [comment]
适配器模式

**Comment by HookTech** [comment]
还会有文章更新吗？

**Comment by draveness** [comment]
> 还会有文章更新吗？

这个版本所有章节基本都写完了，进入 Review 阶段了，随着 Go 语言的演进，不排除未来会有其他更新

**Comment by zou-weidong** [comment]
终于看完了，感谢博主

**Comment by ultramarin4** [comment]
看罢只觉意犹未尽！
大佬有文章讲讲gRPC的吗

**Comment by wojoin** [comment]
博客看完了，书也看完了。下面就去实践了
