### ISSUE TITLE
Kubernetes、集群联邦和资源分发 - 面向信仰编程 · /kuberentes-federation/

### ISSUE THREAD

**Issue by draveness** [draveness/blog-comments#245]
https://draveness.me/kuberentes-federation/

**Comment by zcong1993** [comment]
终于更新了！
第一句话 typo 从比较早的版本就**生成** -> 声称

**Comment by draveness** [comment]
> @zcong1993
> 终于更新了！
> 第一句话 typo 从比较早的版本就**生成** -> 声称

感谢支持啊，确实太久没更新了

**Comment by qiuyuyin** [comment]
左神勤政🥰

**Comment by zcong1993** [comment]
> @draveness
> > @zcong1993
> > 终于更新了！
> > 第一句话 typo 从比较早的版本就**生成** -> 声称
> 
> 感谢支持啊，确实太久没更新了

评论可以试试这个 https://giscus.app/zh-CN 对回复很友好

**Comment by wujunwei** [comment]
支持支持，这篇刚好讲到最近研究的内容

**Comment by imageslr** [comment]
@zcong1993 确实不错。不过现有的都是基于 issue 的评论，想要平移到 discussion 不太方便吧。giscus 这个插件不知道有没有迁移方案。

---

看了下是有的。
